# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n1OOXx64Fvhyk2eOjgSYoqMXdwNiHTwG

#IMPORTING THE LIBRARIES
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""#IMPORTING THE DATASET"""

dataset = pd.read_csv('Auto_Insurance_in_swedan.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values
print(X)
print(Y)

"""#SPLITTING THE DATASET INTO TRAINING SET AND TEST SET"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

"""#FITTING SIMPLE LINEAR REGRESSION MODEL TO TRAINING SET"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

"""#PREDICTING THE TEST SET RESULTS"""

Y_pred=regressor.predict(X_test)
print(Y_pred)

"""#VISUALIZING THE TRAINING SET RESULTS"""

plt.scatter(X_train,Y_train,color="red")
plt.plot(X_train,regressor.predict(X_train),color="blue")
plt.title('NO. OF CLAIMS VS TOTAL PAYEMENTS(TRAINING SET)')
plt.xlabel('NO. OF CLAIMS')
plt.ylabel('TOTAL PAYEMENTS')
plt.show()

"""#VISUALIZING THE TEST SET RESULTS"""

plt.scatter(X_test,Y_test,color="red")
plt.plot(X_train,regressor.predict(X_train),color="blue")
plt.title('NO. OF CLAIMS VS TOTAL PAYEMENTS(Test SET)')
plt.xlabel('NO. OF CLAIMS')
plt.ylabel('TOTAL PAYEMENTS')
plt.show()