# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otAGflWarqfvz1AdCYMnt1bXOcvzwtqY

#IMPORTING THE LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#READING THE DATASET"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:,1:-1].values
Y = dataset.iloc[:,-1].values
print(X)
print(Y)

"""#TRAINING THE WHOLE DATASET ON LINEAR REGRESSION"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X,Y)

"""#VISUALIZING THE LINEAR REGRESSION MODEL"""

plt.scatter(X,Y,color="red")
plt.plot(X,regressor.predict(X),color="blue")
plt.title('TRUTH OR BLUFF(LINEAR REGRESSION)')
plt.xlabel('POSITION LEVEL')
plt.ylabel('SALARY')
plt.show()

"""#TRAINING USING POLYNOMIAL  REGRESSION"""

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X)
linear_reg = LinearRegression()
linear_reg.fit(X_poly,Y)

"""#VISUALIZING THE POLYNOMIAL REGRESSION MODEL"""

plt.scatter(X,Y,color="red")
plt.plot(X,linear_reg.predict(X_poly),color="blue")
plt.title("TRUTH OR BLUFF(POLYNOMIAL REGRESSION)")
plt.xlabel("POSITION LEVEL")
plt.ylabel("SALARY")
plt.show()

"""#PREDICTING THE LINEAR REGRESSION RESULT"""

print(regressor.predict([[6.5]]))

"""#PREDICTING THE POLYNOMIAL REGRESSION RESULT"""

print(linear_reg.predict(poly_reg.fit_transform([[6.5]])))