# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WSr3YD600nbqFheuie300jAfOrc4mSR2

#SIMPLE LINEAR REGRESSION

#IMPORTING LIBRARIES
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""#IMPORTING THE DATASET"""

dataset=pd.read_csv('Salary_Data.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values
print(X)
print(Y)

"""#SPLITTING OF DATASET"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=1/3,random_state=0)
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

"""#TRAINING THE SIMPLE REGRESSION MODEL ON TRAINING SET"""

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

"""#PRDEICTIONG THE TEST SET RESULTS"""

Y_pred=regressor.predict(X_test)
print(Y_pred)

"""#VISUALIZING THE THE TRAINING SET RESULTS"""

plt.scatter(X_train,Y_train,color="red")
plt.plot(X_train,regressor.predict(X_train),color="blue")
plt.title("SALARY VS YEARS OF EXPERIENCE(TRAINING SET)")
plt.xlabel("YEARS OF EXPERIENCE")
plt.ylabel("SALARY")
plt.show()

"""#VISUALIZING  THE TEST SET RESULT"""

plt.scatter(X_test,Y_test,color="red")
plt.plot(X_train,regressor.predict(X_train),color="blue")
plt.title("SALARY VS YEARS OF EXPERIENCE(TEST SET)")
plt.xlabel("YEARS OF EXPERIENCE")
plt.ylabel("SALARY")
plt.show()
