# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ca5U2WtFRibA-Sb99RQP5AyCcmzkpQZp

#IMPORTING THE LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#READING THE DATASET"""

dataset = pd.read_csv('TEMPERATURE_PRESSURE.csv')
X = dataset.iloc[:,1:2].values
Y = dataset.iloc[:,2].values
print(X)
print(Y)

"""#APPLYING THE POLYNOMIAL REGRESSION"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
poly = PolynomialFeatures(degree = 4)
X_poly = poly.fit_transform(X)
poly.fit(X_poly,Y)
regressor.fit(X_poly,Y)

"""#VISUALIZING THE RESULT"""

plt.scatter(X,Y,color = "red")
plt.plot(X,regressor.predict(X_poly),color = "blue")
plt.title("TEMPERATURE VS PRESSURE")
plt.xlabel("TEMPERATURE")
plt.ylabel("PRESSURE")
plt.show()

"""#FINDING THE EQUATION"""

print(regressor.coef_)
print(regressor.intercept_)

"""#PREDICTING THE OUTPUT"""

print(regressor.predict(poly.fit_transform(([[110.0]]))))